name: Release new version to the Maven Central Repository
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Java/Maven Action
        uses: s4u/setup-maven-action@v1.8.0
        with:
          java-version: 11
          maven-version: '3.9.2'

      - name: Set up Sonatype Staging Repository
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "sonatype-nexus-staging", 
              "username": "${env.MAVEN_USERNAME}", 
              "password": "${env.MAVEN_PASSWORD}", 
              "privateKey": "${env.MAVEN_PRIVATE_KEY}", 
              "passphrase": "${env.MAVEN_PASSPHRASE}"
            },
            {
              "id": "gpg.passphrase",
              "passphrase": "${env.MAVEN_PASSPHRASE}",
              "configuration": {}
            }]

      - name: Publish to Apache Maven Central
        run: mvn clean deploy -Prelease -Drevision=${{ github.event.inputs.tag }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Tag release on Github
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }} Release
          draft: false
          prerelease: false
