name: publish-snapshot

on:
  workflow_run:
    workflows:
      - jmeter-maven-plugin-ci
    branches: main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Java/Maven Action
        uses: s4u/setup-maven-action@v1.8.0
        with:
          java-version: 11
          maven-version: '3.9.2'

      - name: Set up Sonatype Snapshots Repository
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          sonatypeSnapshots: true
          servers: |
            [{
              "id": "sonatype-nexus-snapshots", 
              "username": "${env.MAVEN_USERNAME}", 
              "password": "${env.MAVEN_PASSWORD}", 
              "privateKey": "${env.MAVEN_PRIVATE_KEY}", 
              "passphrase": "${env.MAVEN_PASSPHRASE}"
            }]

      - name: Publish to Sonatype Snapshots Repository
        run: mvn clean deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
